# Generated by Django 5.0.6 on 2024-07-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_character_name_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.CharField(choices=[('dummy', 'dummy')], default='dummy', max_length=7),
        ),
        migrations.AddField(
            model_name='character',
            name='plot',
            field=models.CharField(default='defaultplot', max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='stat',
            field=models.JSONField(default=dict),
        ),
    ]
