# Generated by Django 5.0.6 on 2024-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_user_alter_character_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='character',
            name='stat',
            field=models.JSONField(default=list),
        ),
    ]
