# Generated by Django 5.0.6 on 2024-07-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_character_items_alter_character_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=-1),
        ),
    ]
