# Generated by Django 5.0.6 on 2024-07-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_character_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_response',
            field=models.TextField(default=''),
        ),
    ]
