# Generated by Django 5.0.6 on 2024-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_last_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='description',
        ),
        migrations.AddField(
            model_name='log',
            name='ai_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.TextField(blank=True),
        ),
    ]
