# Generated by Django 5.0.6 on 2024-08-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_log_description_log_ai_response_log_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='user_query',
        ),
    ]
