# Generated by Django 5.0.6 on 2024-08-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_user_log_user_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user_query',
        ),
        migrations.AddField(
            model_name='log',
            name='contents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
