# Generated by Django 5.0.6 on 2024-08-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_log_ai_response_remove_log_user_query_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='character',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
