# Generated by Django 5.0.6 on 2024-08-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_log_options_alter_character_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=-1),
        ),
    ]
