# Generated by Django 5.0.6 on 2024-08-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_character_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
