# Generated by Django 5.0.6 on 2024-08-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_character_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='items',
            new_name='inventory',
        ),
    ]
