# Generated by Django 5.0.6 on 2024-08-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_rename_items_character_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipped',
            field=models.JSONField(default=list),
        ),
    ]
